# Generated by Django 3.2.9 on 2021-11-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chessuser',
            options={'ordering': ('-points',)},
        ),
        migrations.AddField(
            model_name='chessuser',
            name='lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chessuser',
            name='win',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chessuser',
            name='points',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='chessuser',
            name='rank',
            field=models.CharField(max_length=20),
        ),
    ]
